name: AzPScontainerAction
on: [workflow_dispatch]

jobs:
  AzPSimageJob:
    runs-on: ubuntu-latest
    steps:
    - name: AzPowerShellStep
      uses: docker://mcr.microsoft.com/azure-powershell:latest
      with:
        entrypoint: pwsh
        args: -Command ls -l ./scripts


# Works
#       entrypoint: pwsh
#       args: -Command Get-Process   

#       args: -File ./scripts/RGquery.ps1  #The argument './scripts/RGquery.ps1' is not recognized as the name of a script file.