name: AzPScontainerAction
on: [workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-powershell:latest
      options: --mount type=bind,source=${{ github.workspace }},target=/github/workspace
    steps:
    - name: Run Azure PowerShell script
      run: pwsh -File /github/workspace/scripts/RGquery.ps1


# Works
#       entrypoint: pwsh
#       args: -Command Get-Process   

#       args: -File ./scripts/RGquery.ps1  #The argument './scripts/RGquery.ps1' is not recognized as the name of a script file.