name: AzPScontainerAction
on: [workflow_dispatch]

jobs:
  AzPSimageJob:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/azure-powershell:latest
      volumes:
        - ${{ github.workspace }}:/github/workspace
          
    steps:
      - name: AzPowerShellStep
        run: pwsh -Command "cd\ ; cd github/workspace; dir" 



# Works------------ But the PowerShell modules aren't installed
#   jobs:
#      AzPSimageJob:
#        runs-on: ubuntu-latest
#        container:
#          image: mcr.microsoft.com/azure-powershell:latest
#        steps:
#        - name: AzPowerShellStep
#          with:
#            entrypoint: pwsh
#            args: -Command "Get-Process; Get-Module -ListAvailable|FT" 
#----------------

#       args: -File ./scripts/RGquery.ps1  #The argument './scripts/RGquery.ps1' is not recognized as the name of a script file.  #4


#       run: pwsh -Command ls -l  #Doesn't show the repository mounted     #5 

#----Run8: Fails to mount
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    container:
#      image: mcr.microsoft.com/azure-powershell:latest
#      volumes:
#        - ${{ github.workspace }}:/github/workspace
#    steps:
#    - name: Run Azure PowerShell script
#      run: pwsh -File /github/workspace/scripts/RGquery.ps1
#----


#9    Same error
#      uses: docker://mcr.microsoft.com/azure-powershell:latest
#      with:
#        entrypoint: pwsh
#        args: -File ./scripts/RGquery.ps1
#      working-directory: ${{ github.workspace }}
#---

#6  Mount options
#  jobs:
#    build:
#      runs-on: ubuntu-latest
#      container:
#        image: mcr.microsoft.com/azure-powershell:latest
#        options: --mount type=bind,source=${{ github.workspace }},target=/github/workspace
#      steps:
#      - name: Run Azure PowerShell script
#        run: pwsh -File /github/workspace/scripts/RGquery.ps1  
#-----------