name: AzPScontainerAction
on: [workflow_dispatch]

jobs:
  AzPSimageJob:
    runs-on: ubuntu-latest
    steps:
    - name: AzPowerShellStep
      uses: docker://mcr.microsoft.com/azure-powershell:latest
      with:
        entrypoint: pwsh
        args: -Command Get-Process


# Works
#       entrypoint: pwsh
#       args: -Command Get-Process        