name: AzPScontainerAction
on: [workflow_dispatch]

jobs:
  AzPSimage:
    runs-on: ubuntu-latest
    steps:
    - name: Azure PowerShell command
      uses: docker://mcr.microsoft.com/azure-powershell:latest
      with:
        entrypoint: pwsh
        args: -Command Get-Process
