name: GHActions PSAzConnect Workflow
on: [workflow_dispatch]
jobs:      
  AzConnectionJob:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: AzConnectionStep
      shell: pwsh
      run: .\AzPS\AzConnect.ps1 ${{ vars.TenantId }} ${{ vars.SubscriptionId }} ${{ vars.ClientId }} ${{secrets.PSGitHubActionsv2_SPN_PSWD}}
      
      

# "${{ vars.VAR }}"     #quotes not needed
# run: pwsh .\AzPS\RGquery.ps1  ${{ fromJson(vars.AZCONNECT).clientId }}  #Works too
# run: .\AzPS\RGquery.ps1  ${{ fromJson(vars.AZCONNECT).clientId }}  #Works if shell is added

# run: .\AzPS\RGquery.ps1  ${{ vars.TenantId }} ${{ vars.SubscriptionId }} ${{ vars.ClientId }} ${{secrets.PSGitHubActionsv2_SPN_PSWD}}  #Working version
#params and the variable sequence need to match

# run: .\AzPS\RGquery.ps1  @${{ vars.AZCONNECT }} -SPNPswd ${{secrets.PSGitHubActionsv2_SPN_PSWD}}  #Splatting Didn't work
# Error: Exception calling ".ctor" with "2" argument(s): "Cannot process argument because the value of argument
#     | "userName" is not valid. Change the value of the "userName" argument and run the operation again."

# run: .\AzPS\RGquery.ps1 ([hashtable]${{ vars.AzConnect }}) -SPNPswd ${{secrets.PSGitHubActionsv2_SPN_PSWD}} 
# Error: Cannot convert the value of type  "System.Management.Automation.ScriptBlock" to type "System.Collections.Hashtable".