name: SPNAuth23
on: [workflow_dispatch]
jobs:
  SPNAuth23:
    runs-on: windows-latest
    steps:    
    - name: Login via Az module
      uses: azure/login@v1
      with:
        creds: ${{secrets.PSGitHubActionsv2JSONSecret}}
        enable-AzPSSession: true 

    - name: Run Azure PowerShell script
      uses: azure/powershell@v1
      with:
        inlineScript: Get-AzResourceGroup|FT
        azPSVersion: 'latest'


# inlineScript: Get-AzResourceGroup|FT       #Works  
# ./AzPS/RGquery.ps1  #forward slash didn't work
# The term './scripts/RGquery.ps1' is not recognized as a name of a cmdlet

# Run and shell don't work. Error: Unexpected input(s) 'run', 'shell', valid inputs are ['inlineScript', 'azPSVersion', 'errorActionPreference', 'failOnStandardError', 'githubToken']