name: PSGitHubActions Workflow
on: [workflow_dispatch]
jobs:      
  RGCreate:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: query resource group
      run: powershell .\AzPS\RGquery.ps1
