name: GHActions PSAzConnect Workflow
on: [workflow_dispatch]
jobs:      
  AzConnectionTest:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v3
    - name: query resource group
      run: |
        .\AzPS\RGquery.ps1  ${{ fromJson(vars.AZCONNECT).clientId }}
  shell: pwsh



    #  run: pwsh .\AzPS\RGquery.ps1  ${{ fromJson(vars.AZCONNECT).clientId }}
