name: PSGitHubActions Workflow
on: [workflow_dispatch]
jobs:      
  RGQuery:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v2
    - name: query resource group
      run: pwsh .\AzPS\RGquery.ps1
